# Generated by Django 4.2.1 on 2023-06-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='nom_plante',
            field=models.CharField(default='plante', max_length=255),
        ),
    ]
